### ISSUE TITLE
list of open websockets

### ISSUE THREAD

**Issue by matteofattore-nextage** [jrief/django-websocket-redis#78] opened 2015-02-04 14:11 UTC
I need the list of currently open websockets. In my application a timed process sends data to the browsers through websockets. the generation of these data is time-consuming. I would not want to prepare data to be sent through websocket that no user is connected on.

Has someone developed something like this?

**Comment by jrief** [comment] 2015-02-04 14:50
Duplicate of #11

**Closed by jrief** 2015-02-04 14:50 UTC
